### PR TITLE
Add staging CD jobs

### PR DESCRIPTION
**Pull request by gwenwindflower**
Adds GHAs to call the Staging Deploy jobs for BQ and SF on merge to `staging`.

This supports the change to make Staging the default branch in Jaffle Shop (already done), and completes the process of getting us to the following state:
- :bridge_at_night: **Feature branches branch off Staging**
- :sunrise: **Feature branches are PR'd against Staging** and run CI jobs via API call across all active adapters (currently SF and BQ) in the Staging Environment
- :new: **PRs are merged into Staging**, kicking off a CD build job in Staging (our default build command is `dbt build --exclude "resource_type:seed" because seeds are depended on as a source, and running a regular build will create a race condition where some models beat their source seeds into the warehouse and cause failing tests)
- :rocket: **When we're ready for a Jaffle Shop Release we merge Staging into Main** kicking off CD jobs via API call in the Prod Environment across all active adapters
- :nerd_face: **Dev Environments in dbt Cloud auto defer to Staging**, as we've set that up as a Staging Environment in Cloud

### CODE REVIEW

**Comment by joellabes** [comment]
> * our default build command is `dbt build --exclude "resource_type:seed" because seeds are depended on as a source, and running a regular build will create a race condition where some models beat their source seeds into the warehouse and cause failing tests

Is this because there are models whose dependencies are not being forced? Wouldn't it be better to [force the dependency](https://docs.getdbt.com/reference/dbt-jinja-functions/ref#forcing-dependencies) than babysit which nodes get built outside of dbt itself?

**Review by joellabes — APPROVED** [review]

**Comment by gwenwindflower** [comment]
> > * our default build command is `dbt build --exclude "resource_type:seed" because seeds are depended on as a source, and running a regular build will create a race condition where some models beat their source seeds into the warehouse and cause failing tests
> 
> Is this because there are models whose dependencies are not being forced? Wouldn't it be better to [force the dependency](https://docs.getdbt.com/reference/dbt-jinja-functions/ref#forcing-dependencies) than babysit which nodes get built outside of dbt itself?

so seeds run in parallel with everything else, if a source is pointed at a seed's output, and the seed is..._seeding_ into the db still, bad stuff happens. there are no models to force the deps on, as they're sources rather than models. the Big Fix would be if seeds were treated as a proper part of the DAG, which there's an issue for and i've brought up with Doug and Jerco. i think that would make a lot of sense. 

i have an alternative fix i'm toying with i'll send you as a Loom, would be interested in your thoughts on it, but it's more of a tradeoff than a fix.

**Comment by joellabes** [comment]
Wouldn't this work? 

```
#seeds/my_seed.csv
id,name
1,winnie
2,joel
```

```yaml
#models/sources.yml
sources:
  - name: seeds
    tables: 
        - name: my_seed
          # etc
```

```sql
-- models/stg_my_seed.sql

-- depends_on: {{ ref('my_seed') }}
with seed as (
  select * from {{ source('seeds', 'my_seed') }}
)
-- etc
```

Maybe not a good idea as I write it out if this is meant to be a best practice demo

**Comment by gwenwindflower** [comment]
@joellabes oh yea i think you're right that should work, but yea maybe not ideal for beginners 🤔

**Pull request merged**
